bin/johnny generate 30 soup
bin/johnny generate 30 forest
bin/johnny generate 30 president
bin/johnny generate 30 machine
bin/johnny generate 30 banana
bin/johnny generate 30 bomb
bin/johnny generate 30 beast
bin/johnny generate 30 china
bin/johnny generate 30 heat
bin/johnny generate 30 sailing
